name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  foundry:
    strategy:
      fail-fast: true

    name: Simulate solutions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Simulate script without broadcasting
        run:  forge script script/BlockNumberIssueScript.sol:BlockNumberScript -vvvv --fork-url=$FORK_URL --private-key=$PRIVATE_KEY --broadcast --slow
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}

      - name: Broadcast transactions (will fail)
        run:  forge script script/BlockNumberIssueScript.sol:BlockNumberScript -vvvv --fork-url=$FORK_URL --private-key=$PRIVATE_KEY --broadcast --slow
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}

